[package]
name = "day13"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "part1"
test = true

[[bin]]
name = "part2"
test = true

[dependencies]
nalgebra = "0.33.2"
ndarray = "0.16.1"
nom = { workspace = true }
